server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mail:
    username: jyha153@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 295

dooray:
  api:
    token: ${DOORAY_API_TOKEN}
    host: https://api.dooray.com/

jwt:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}

service:
  user-url: ${USER_URL}
  front-url: ${FRONT_URL}

logging:
  level:
    root: debug

token:
  access:
    valid-time: 900000
  refresh:
    valid-time: 604800000