spring:
  application:
    name: token-service

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8091/login/oauth2/code/github
            scope: read:user, user:email
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8091/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    root: debug
