spring:
  application:
    name: token-service

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_ID_GITHUB}
            client-secret: ${OAUTH_SECRET_GITHUB}
            redirect-uri: ${REDIRECT_URL_GITHUB}
            scope: read:user, user:email
          google:
            client-id: ${OAUTH_ID_GOOGLE}
            client-secret: ${OAUTH_SECRET_GOOGLE}
            redirect-uri: ${REDIRECT_URL_GOOGLE}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    root: debug
