server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 295

jwt:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}

service:
  user-url: ${USER_URL}
  front-url: ${FRONT_URL}

logging:
  level:
    root: debug

