spring:
  application:
    name: token-service

  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8091
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: info