### logout
POST http://localhost:8091/login
Content-Type: application/json

{
  "email": "unit@email.com",
  "password": "1"
}

### refresh
POST http://localhost:8091/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJxYXciLCJpYXQiOjE3MzI4MDM0NzMsImV4cCI6MTczMjgwNzA3M30.gaDcOM6BADl2-IgmYQu2-_i74Qy2mBnCyOEfcHjRHO1lxyXUezpM-utRDt1gED8lWat7fo0aZCy_BUmyiicjk2GdlvxkXso2fD-9yKwShgcdhNU7FPW6zl0kzZVQO-LZ-pBsnUx2XfUGtHqvzgnHcEJAn6_v3y2YLna7ew_h8mTF_Ir6Em30znVWySCFTUK-UJDYNueBWg7DPVGlmyIrcHP-Hf5y1tWYpQS3zEhpGSFd7ZIMVKL6bZu6rXb-CpzkOySOE2si3VFoNTjN8Ok1xYfPswuPSzG6KXVngVRH0ySWt7x21wOD8VVMNLR2plBz3_pQzlQ_w73aaMTzN7ZLhA
Cookie: refreshToken=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJxYXciLCJpYXQiOjE3MzI4MDM0NzMsImV4cCI6MTczMzQwODI3M30.rRAPXBS-Dvix5WHZMcRNkwWejsi-_EQ34rSeqyhK59m6Fer25zV1SsdfFzzgShYDRnnBil8zPgYJnlCVuBOaRf6TRDq0lBQPcOwwe8IBreS9chHeEzBuKq1cX-4vNXO1TUOrLElaw_ILU6sNCZ3NGUwNaEPq5puVfb3d8OnkyX07WuST3vreKkvyN5PeNcXqWS8Tq0OXr9OzHcT8VCnusJNjDyPVClrvgCevYJPKUrTI_2jVM2_b7byASpdNFxztRsrFyU1AxwVerM7PWkKBoLD2wi8R-AlhbOOO_EwCfgxmhqABI8YMrWgo8V9DjD1FtmP2ysG4Bx0P5RTD2j48vQ


### logout
POST http://localhost:8091/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJxYXciLCJpYXQiOjE3MzI4MDM0NzMsImV4cCI6MTczMjgwNzA3M30.gaDcOM6BADl2-IgmYQu2-_i74Qy2mBnCyOEfcHjRHO1lxyXUezpM-utRDt1gED8lWat7fo0aZCy_BUmyiicjk2GdlvxkXso2fD-9yKwShgcdhNU7FPW6zl0kzZVQO-LZ-pBsnUx2XfUGtHqvzgnHcEJAn6_v3y2YLna7ew_h8mTF_Ir6Em30znVWySCFTUK-UJDYNueBWg7DPVGlmyIrcHP-Hf5y1tWYpQS3zEhpGSFd7ZIMVKL6bZu6rXb-CpzkOySOE2si3VFoNTjN8Ok1xYfPswuPSzG6KXVngVRH0ySWt7x21wOD8VVMNLR2plBz3_pQzlQ_w73aaMTzN7ZLhA
Cookie: refreshToken=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJxYXciLCJpYXQiOjE3MzI4MDM0NzMsImV4cCI6MTczMzQwODI3M30.rRAPXBS-Dvix5WHZMcRNkwWejsi-_EQ34rSeqyhK59m6Fer25zV1SsdfFzzgShYDRnnBil8zPgYJnlCVuBOaRf6TRDq0lBQPcOwwe8IBreS9chHeEzBuKq1cX-4vNXO1TUOrLElaw_ILU6sNCZ3NGUwNaEPq5puVfb3d8OnkyX07WuST3vreKkvyN5PeNcXqWS8Tq0OXr9OzHcT8VCnusJNjDyPVClrvgCevYJPKUrTI_2jVM2_b7byASpdNFxztRsrFyU1AxwVerM7PWkKBoLD2wi8R-AlhbOOO_EwCfgxmhqABI8YMrWgo8V9DjD1FtmP2ysG4Bx0P5RTD2j48vQ
