### user 저장
POST http://localhost:8090/user
Content-Type: application/json

{
  "id": "1",
  "email": "qaw@email.com",
  "username": "aw",
  "password": "123",
  "auth": "ADMIN",
  "provider": ""
}

### email(login id)로 유저조회
GET http://localhost:8090/user?email=qaw@email.com
Content-Type: application/json